import type { Metadata } from "next";
import "./globals.css";
import Providers from "./src/components/Providers";

export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="" >
      <body className="bg-lightBlue dark:bg-darkBg text-lightGray dark:text-white font-poppins">
        <Providers>
          {children}
        </Providers>
        <div id="toast" className="fixed top-2 right-2 bg-white dark:bg-darkBlue px-4 py-2 rounded hidden text-white font-semibold">hello world</div>
      </body>
    </html>
  );
}
